name: Deploy Resume to Pages

on:
  push:
    branches: [main, master]

permissions:
  contents: write

# https://jsonresume.org/themes
env:
  THEME: consultant-polished
  THEME_PACKAGE: "@jsonresume/jsonresume-theme-consultant-polished"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install CLI and Theme
        run: |
          npm install -g resume-cli
          npm i ${{ env.THEME_PACKAGE }}

      - name: Generate HTML
        run: |
          # This runs the CLI to convert resume.json to index.html using the installed theme
          npx resume export index.html --theme ${{ env.THEME }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true # Keeps your resume.json available
