name: Deploy Resume to Pages

on:
  push:
    branches: [main, master]

permissions:
  contents: write

# https://jsonresume.org/themes
env:
  THEME_PACKAGE: jsonresume-theme-even
  THEME_NAME: even

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install CLI and Theme
        run: |
          npm install -g resume-cli
          npm install ${{ env.THEME_PACKAGE }}

      - name: Generate HTML
        run: |
          npx resume export index.html --theme ${{ env.THEME_NAME }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
